### PR TITLE
Remake measured data objects

### LINKED ISSUE #101: Remake EnergyUsage, EnergyProduction
These objects need to parallel the EnergyACMeasurement pattern. Used in PVSystem and BatterySystem.

### PR DESCRIPTION
**Pull request by cwhanse**
Closes #101 

Adds object Production. Removes EnergyProductions.

### CODE REVIEW

**Review by jrippingale — APPROVED** [review]
Looks like the foundation we need :-)

**Review by jrippingale — APPROVED** [review]
Looks as I expected :-)

**Comment by jrippingale** [comment]
Is this a problem?  Did we miss a "Value" somewhere?
image

**Comment by cwhanse** [comment]
I don't know the cause of that failure and I also don't know how to track it down. It's in the check that we wrote to verify correct JSON, enforce spelling convention, etc. So despite the failure, we have a valid JSON file that conforms to Open API. I think we can proceed.

**Pull request merged**
