### PR TITLE
Availabilities update

### PR DESCRIPTION
**Pull request by kevinkirkl3y**
Changed branch name for clarity. I manually addressed the issue caused by they OB Editor bug. Availabilities now has a description applied to it. Continues PR #220

### CODE REVIEW

**Comment by kevinkirkl3y** [comment]
Closes Issue #215

**Comment by cwhanse** [comment]
@kevinkirkl3y if you open the changed json file in the editor, do nothing but save it again, does this change survive?

**Comment by kevinkirkl3y** [comment]
@cwhanse Yeah, it didn't make any changes to the file.

**Review by jrippingale — APPROVED** [review]
Do we need a What's New file also?

**Review by jrippingale — APPROVED** [review]

**Comment by cwhanse** [comment]
Superceded by #226

**Pull request closed without merging**
