### PR TITLE
Adds StandardTypeItemType and adds updated Enums

### LINKED ISSUE #172: Enumeration for standards documents
Standards have the following metadata:
- Standard number, e.g., IEC61724 which described performance indexes.
- Sometimes a standard in published in parts, e.g., IEC61724-1, -2, -3
- Revision, version or date, e.g., IEC61724-1 ed. 1.0 2017-03
- Publication body, e.g., International Electrotechnical Commission.

Nomenclature and naming patterns are not consistent among standards bodies (IEC, IEEE, UL, ASTM, EN) [here](https://www.usaid.gov/energy/powering-health/technical-standards/photovoltaic-systems)'s a partial list.

OB needs to distinguish between standard revisions (e.g., IEC61724-1 ed. 1.0 2017 and IEC61724-1 ed. 2.0 2021), because certification to an older version doesn't imply certification to newer versions.

Values of standards are currently enumerated by CertificationTypeProductItemType, using only the standard number e.g. IEC61215.

Standards are used for purposes other than certification of products.

- Should OB have a general enumeration of standards, and use OB Item Type Groups to subset the values for different purposes (product certification, commissioning, performance monitoring)
- Should the enumerated value be extended to include part, version and date, e.g., IEC61724_1_ed1_2017? Should avoid any special character other than underscore, so how does OB handle ed1.0 vs. ed1.1 (if such a case arises)?
- If the value is extended with Part, is there a role for an "all parts" value, e.g. IEC61724? This presumes that all parts share a common version or date.

### PR DESCRIPTION
**Pull request by kevinkirkl3y**
Closes #172

### CODE REVIEW

**Comment by blizita** [comment]
Note to talk through NEC690 as an example of overlapping standard

**Comment by reepoi** [comment]
The StandardTypeItemType enums plus the CertificationTypeProductItemType enums cover all of the `standard name/number` values from the CEC data. Should we include all the enums from CertificationTypeProductItemType in the enums of StandardTypeItemType? `UL1741SA` is a value from the CEC data that is in CertificationTypeProductItemType, but not in StandardTypeItemType.

Also, for [grid support solar inverters](https://solarequipment.energy.ca.gov/Home/InverterSolarList), the CEC lists whether a product was tested according to a range of sections of a standard. For example, `UL 1741 SA8-SA13`. To communicate that a product is certified under this range, one option is to add an enum for each section (`UL1741SA8`,...,`UL1741SA13`) to StandardTypeItemType, and then create a ProdCertification for each of the sections.

**Comment by kevinkirkl3y** [comment]
@reepoi I have added UL1741SA to the StandardTypeItemType Enums. In reference to the individual section that are noted, there is the element CertificationTypeSections within the taxonomy and designed to serve this specific purpose. It currently isn't a member of any objects but could quickly be added ProdCertification if it meets your requirements.

**Comment by reepoi** [comment]
@kevinkirkl3y I have the list of the remaining enums to add to the StandardTypeItemType:
- For ProdModule data
  - add UL 1703
- For ProdEnergyStorageSystem data
  - add UL 9540:2016
  - add UL 9540:2020
  - add JA12
    - This is also in CertificationTypeProductItemType [here](https://github.com/Open-Orange-Button/Orange-Button-Taxonomy/blob/0c51dac431d4f6a5fde563c62a23c3662ba2ff32/Master-OB-OpenAPI.json#L16294), and the CEC uses it to refer to the 2019 Building Energy Efficiency Standards' Reference Joint Appendix 12

Also, I saw that the CEC does not use UL 1741 SA Section 16, so we could skip adding that section enum for now.

**Comment by kevinkirkl3y** [comment]
> 

Taos, I have added the requested UL 9450 and JA12 Standards

**Comment by cwhanse** [comment]
@kevinkirkl3y to discuss: 

- UL9540 (2016, 2020 and 2021; I only find 2020 as a document date). The titles don't appear correct.
- CSIP_NRTL isn't a standard per se, its a report from a NRTL that a device satisifies CSIP. There must be a use case that requested this value; lets discuss.

**Review by cwhanse — APPROVED** [review]

**Review by reepoi — APPROVED** [review]

**Pull request merged**
