### PR TITLE
Create OperatingReport

### LINKED ISSUE #102: Remake OperatingReport from current MonthlyOperatingReport
After #101 is merged.

### PR DESCRIPTION
**Pull request by cwhanse**
Closes #102 

Adds Objects: OperatingReport, ExpectedEnergyModel, ForecastEnergyModel, PerformanceRatio.

Adds Elements: EnergyModelID, PerfRatio, EnergyACModeled, EnergyACCurtailed, Insolation

### CODE REVIEW

**Comment by cwhanse** [comment]
@jrippingale should we inherit Scope or attach Scope? I think we could inherit. The difference:

Inherit:

OperatingReport.Description, .ScopeType, .ScopeID, etc.

Attach:

OperatingReport.Scope.Description, .ScopeType, .ScopeID, etc.

**Comment by jrippingale** [comment]
Let's make sure we are consistent with how this is done everywhere else.  Also, if we inherit, then "Description" could be ambiguous...  We may need to attach due to that field...

**Comment by cwhanse** [comment]
Add EnergyACOutage

**Comment by cwhanse** [comment]
Add PerformanceIndex, Availability, Yield (requires new unit kWhr_per_kW)

**Review by jrippingale — APPROVED** [review]
Looks great!

**Pull request merged**
