### PR TITLE
add ValueNumber etc.

### PR DESCRIPTION
**Pull request by cwhanse**
Aligns JSON data type with TaxonomyElementType.  Requires change to OB Editor Open-Orange-Button/Orange-Button-Editor#3.

### CODE REVIEW

**Comment by cwhanse** [comment]
Any objections to merge?  The editor change is now merged, so the Taxonomy can move forward.

**Comment by jrippingale** [comment]
Please do merge so we can utilize the new functionality!

Thank you!
jan


[image: Blu Banyan] <https://www.blubanyan.com/>

[image: O-NetSuite Solution Partner]
Jan Rippingale
CEO
Blu Banyan <https://blubanyan.com/>

m:  <707.234.5395>707.234.5395
e: ***@***.***

**Review by jrippingale — APPROVED** [review]
Clarity is better!  Nice!

**Comment by cwhanse** [comment]
We need to build onto this PR to add the data type for an array-valued element. See [OpenAPI 3.0 guide](https://swagger.io/docs/specification/data-models/data-types/#array).

**Comment by cwhanse** [comment]
This PR can't be merged as is, because it deletes the Value primitive but doesn't replace that primitive in every element.

**Pull request merged**
